---
- hosts: all
  tasks:
    - name: 'Bootstrap basic PPAs and install applications.'
      become: yes
      block:
        - apt_key:
            url: https://dl-ssl.google.com/linux/linux_signing_key.pub
            state: present
        - apt_repository:
            repo: "{{ item }}"
            state: present
            update_cache: true
          with_items:
              - 'ppa:git-core/ppa'
              - 'ppa:mozillateam/firefox-next'
              - 'ppa:webupd8team/terminix'
              - 'ppa:webupd8team/java'
              - 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main'
        - shell: 'echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections'
        - apt:
            name: "{{ item }}"
            state: latest
          with_items:
              - pass
              - git
              - neovim
              - firefox
              - google-chrome-beta
              - tilix
              - oracle-java8-installer
              - fonts-hack-ttf
        - apt:
            deb: https://github.com/onivim/oni/releases/download/v0.2.18/Oni-0.2.18-amd64-linux.deb
        - apt:
            autoclean: yes
            autoremove: yes
    - name: 'Download the Toolbox.'
      block:
          - get_url:
              url: http://download.jetbrains.com/toolbox/jetbrains-toolbox-1.6.2914.tar.gz
              dest: /tmp/jetbrains-toolbox.tar.gz
              mode: 0700
          - unarchive:
              src: /tmp/jetbrains-toolbox.tar.gz
              dest: /tmp
          - command: /tmp/jetbrains-toolbox-1.6.2914/jetbrains-toolbox
    - name: 'Download bash-it.'
      git:
        repo: https://github.com/Bash-it/bash-it.git
        dest: "{{ ansible_env.HOME }}/.bash-it"
        depth: 1
