---
- hosts: all
  tasks:
    - name: 'Bootstrap basic PPAs and install applications.'
      become: yes
      block:
        - apt_key:
            url: https://dl-ssl.google.com/linux/linux_signing_key.pub
            state: present
        - apt_repository:
            repo: 'ppa:git-core/ppa'
            state: present
        - apt_repository:
            repo: 'ppa:mozillateam/firefox-next'
            state: present
        - apt_repository:
            repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main'
            state: present
            filename: 'google-chrome-beta'
        - apt_repository:
            repo: 'ppa:webupd8team/terminix'
            state: present
        - apt_repository:
            repo: 'ppa:webupd8team/java'
            state: present
        - shell: 'echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections'
        - apt: update_cache=yes
        - apt: name=pass state=latest
        - apt: name=git state=latest
        - apt: name=neovim state=latest
        - apt: name=firefox state=latest
        - apt: name=google-chrome-beta state=latest
        - apt: name=tilix state=latest
        - apt: name=oracle-java8-installer state=latest
        - apt: name=fonts-hack-ttf state=latest
        - apt:
            deb: https://github.com/onivim/oni/releases/download/v0.2.18/Oni-0.2.18-amd64-linux.deb
        - apt:
            autoclean: yes
        - apt:
            autoremove: yes
    - name: 'Download the Toolbox.'
      block:
          - get_url:
              url: http://download.jetbrains.com/toolbox/jetbrains-toolbox-1.6.2914.tar.gz
              dest: /tmp/jetbrains-toolbox.tar.gz
              mode: 0700
          - unarchive:
              src: /tmp/jetbrains-toolbox.tar.gz
              dest: /tmp
          - command: /tmp/jetbrains-toolbox-1.6.2914/jetbrains-toolbox-1.6.2914
